src/com/example/entity/Product.java
package com.example.entity;

public class Product {
    private int id;
    private String name, pro_desc;

    public Product(int id, String name, String pro_desc) {
        this.id = id;
        this.name = name;
        this.pro_desc = pro_desc;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPro_desc() {
        return pro_desc;
    }

    public void setPro_desc(String pro_desc) {
        this.pro_desc = pro_desc;
    }
}

src/com/example/entity/User.java
package com.example.entity;

public class User {
    private int id;
    private String  username, password;

    public User(int id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

src/com/example/model/LoginBean.java
package com.example.model;

import com.example.da.UserDataAccess;
import com.example.entity.User;

import java.sql.SQLException;
import java.util.List;

public class LoginBean {
    private int id;
    private String name, username, password;

    public LoginBean() {
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

//    private List<User> getUser() throws SQLException, ClassNotFoundException {
//        return new UserDataAccess().getUser(username, password);
//    }

    public boolean checkLogin() {
        UserDataAccess usersDataAccess = new UserDataAccess();
        try {
            List<User> users = usersDataAccess.getUser(username, password);
            return !users.isEmpty();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return false;
    }
}

src/com/example/model/ProductBean.java
package com.example.model;

import com.example.da.ProductDataAccess;
import com.example.entity.Product;

import java.sql.SQLException;
import java.util.List;

public class ProductBean {
    public List<Product> getProducts() throws SQLException, ClassNotFoundException {
        return new ProductDataAccess().getAllProduct();
    }
}

src/com/example/controller/LoginController.java
package com.example.controller;

import com.example.model.LoginBean;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

@WebServlet(name = "LoginController")
public class LoginController extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String username = request.getParameter("username");
        String password = request.getParameter("password");

        LoginBean loginBean = new LoginBean();
        loginBean.setUsername(username);
        loginBean.setPassword(password);

        boolean status = loginBean.checkLogin();
        HttpSession session = request.getSession();
        if(status) {
            session.setAttribute("bean", loginBean);
            response.sendRedirect("create_product.jsp");
        } else {
            response.sendRedirect("index.jsp?msg= Please check your user name or password!");
        }
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }
}

src/com/example/controller/ProductController.java
package com.example.controller;

import com.example.da.ProductDataAccess;
import com.example.entity.Product;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.SQLException;

@WebServlet(name = "CreateProductController")
public class ProductController extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String name = request.getParameter("name");
        String description = request.getParameter("description");

        Product product = new Product(1, name, description);

        ProductDataAccess createProduct = new ProductDataAccess();
        try {
            createProduct.createProduct(product);
            response.sendRedirect("list_product.jsp");
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }
}

web/create_product.jsp
<%--
  Created by IntelliJ IDEA.
  User: vuduy
  Date: 6/5/2020
  Time: 3:20 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
  <c:if test="${sessionScope.bean == null}">
    <jsp:forward page="index.jsp"></jsp:forward>
  </c:if>
  <title>Create product</title>
</head>
<body>

  <h2>Create product</h2>
  <form action="create_product" method="post">
    <div>
      <span>Name</span>
      <input type="text" name="name" />
    </div>
    <div>
      <span>Description</span>
      <input type="text" name="description" />
    </div>
    <div>
      <button>Create</button>
    </div>
  </form>
</body>
</html>

web/index.jsp
<%--
  Created by IntelliJ IDEA.
  User: vuduy
  Date: 6/5/2020
  Time: 3:01 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <title>Login</title>
  </head>
  <body>
  <h2>Login Form</h2>
  <div>
    <form action="login" method="post">
      <div>
        <span style="color: red">
        <c:out value="${param.msg}"/>
      </span>
      </div>
      <div>
        Username: <input type="text" name="username">
      </div>
      <div>
        Passowrd: <input type="password" name="password">
      </div>
      <div>
        <button>Login</button>
      </div>
    </form>
  </body>
</html>

web/list_product.jsp
<%--
  Created by IntelliJ IDEA.
  User: vuduy
  Date: 6/5/2020
  Time: 11:49 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix ="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix ="sql" uri="http://java.sun.com/jsp/jstl/sql" %>
<html>
<head>
  <title>Title</title>
</head>
<body>
  <jsp:useBean id="display" class="com.example.model.ProductBean"/>
  <h2>List of Products</h2>
  <table border="1" >
    <tr>
      <td>ID</td>
      <td>Name</td>
      <td>Description</td>
    </tr>
    <c:forEach  items="${display.products}" var="product">
      <tr>
        <td><c:out value="${product.id}"/></td>
        <td><c:out value="${product.name}"/></td>
        <td><c:out value="${product.pro_desc}"/></td>
      </tr>
    </c:forEach>
  </table>
</body>
</html>